name: "Release dev container features & Generate Documentation"
on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: "Publish Features"
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./src"
          generate-docs: "true"
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR for Documentation (Optional)
        id: push_image_info
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          echo "Checking for documentation updates..."
          
          # Configure git
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          git config pull.rebase false
          
          # Check if there are any changes
          if git diff --quiet && git diff --cached --quiet; then
            echo "No documentation changes detected. Skipping PR creation."
            exit 0
          fi
          
          # Create branch and commit changes
          branch=automated-documentation-update-$GITHUB_RUN_ID
          git checkout -b $branch
          message='Automated documentation update'
          
          # Add and commit changes
          git add */**/README.md
          if git diff --cached --quiet; then
            echo "No documentation files to commit. Skipping PR creation."
            exit 0
          fi
          
          git commit -m 'Automated documentation update [skip ci]'
          
          # Push and create PR
          git push origin "$branch"
          
          # Try to create PR, but don't fail if we can't
          if command -v gh &> /dev/null; then
            gh pr create --title "$message" --body "$message" || echo "Failed to create PR automatically. You can create it manually at: https://github.com/${{ github.repository }}/compare/$branch"
          else
            echo "GitHub CLI not available. Create PR manually at: https://github.com/${{ github.repository }}/compare/$branch"
          fi 